name: DevOps GitOps End-to-End Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configura o Node.js para rodar testes
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and Run Tests
      run: |
        cd app
        npm install
        # Aqui rodariam os testes automatizados (ex: npm test)

    # 3. Faz o Setup do Docker Buildx (ferramenta avançada de build)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4. Faz o build da imagem real da aplicação
    - name: Build Docker Image
      run: |
        docker build -t meu-usuario-docker/gitops-api-app:${{ github.sha }} .
        docker tag meu-usuario-docker/gitops-api-app:${{ github.sha }} meu-usuario-docker/gitops-api-app:latest

    # 5. O Passo do GitOps (A mágica do CD)
    # Em um cenário real, aqui usaríamos um Token para atualizar a tag da imagem
    # dentro da pasta 'k8s-manifests/dev/deployment.yaml' automaticamente.
    - name: Simulate GitOps Manifest Update
      run: |
        echo "Modificando o manifesto de Dev com a nova tag da imagem: ${{ github.sha }}"
        echo "O ArgoCD vai ler essa alteração e aplicar no Kubernetes automaticamente!"

